### ISSUE TITLE
Upgrade Images to use Terraform 0.13

### ISSUE THREAD

**Issue by Spazzy757** [kbst/terraform-kubestack#124]
We came into an issue where there was a requirement to use TF 0.13, I would have thought it would have been an easy switch (just switch out the KubeStack Docker image with a Custom one that has TF 0.13 installed). The issue arises that the KubeStack makes use of Kubestacks custom Kustomize Terraform provider which is installed in the same container. The pathway for [custom terraform providers has been changed](https://www.terraform.io/upgrade-guides/0-13.html#new-filesystem-layout-for-local-copies-of-providers). So you need to dig into Kubestack and pull out the Dockerfile and update it accordingly in order to get it to work. 

There where two problems with this:
- The KubeStack Dockerfile setup is quite layered so it was difficult to pinpoint the exact places to make the change
- You lose the ability to just pull Kubestacks image and have to maintain your own

**Comment by pst** [comment]
0.13 compatibility will be the focus of the next Kubestack release, now that v0.10.0-beta.0 is out and the local development support released.

As a first step, the kustomize provider is now available from the Terraform registry. https://registry.terraform.io/providers/kbst/kustomize/latest

**Comment by Spazzy757** [comment]
This is awesome thank you!

**Comment by pst** [comment]
Now testing: https://github.com/kbst/terraform-kubestack/pull/139

**Comment by pst** [comment]
Release [`v0.11.0-beta.0` completes the upgrade](https://github.com/kbst/terraform-kubestack/releases/tag/v0.11.0-beta.0)

**Comment by Spazzy757** [comment]
Awesome Thanks @pst!
