### ISSUE TITLE
Make the Setup of the Ingress More Modular

### ISSUE THREAD

**Issue by Spazzy757** [kbst/terraform-kubestack#125]
There are some instances where the networking setup requires different approaches to what KubeStack has (for instance running the cluster using Cloudflare as the DNS). it would be great to pull out the Ingress setup and make it more modular so you could have an opt-In approach.

**Comment by pst** [comment]
Opt-in would be a breaking change, so instead I went with opt-out. By default, the ingress setup will still be provisioned. But you can now overwrite this by setting `disable_default_ingress = true` in `config.auto.tfvars`.

This allows users to either not have ingress at all. Or disable the default and roll their own.
