### ISSUE TITLE
Make Workspace Names Configurable

### ISSUE THREAD

**Issue by Spazzy757** [kbst/terraform-kubestack#126]
While the Ops/Apps names are valid and I understand the theory behind it. Some companies have very strict naming patterns to identify between production and non-production (also some companies are pedantic for instance all env's must have 3 letters, prd, stg). It would be great if you could switch out the default workspace names in order to allow for companies with strict naming patterns tp not move away from their best practices

**Comment by pst** [comment]
I've left an example and some hints in the commit message how you can achieve this with the new implementation.
