### ISSUE TITLE
AKS: Enable CNI/Advanced Networking Configuration

### ISSUE THREAD

**Issue by feend78** [kbst/terraform-kubestack#131]
**Enhancement Request:**

_As a user, I would like to configure my Kubestack environment in Azure with CNI/Advanced Networking Config to allow greater control over networking resources._

**Background**

We are looking to use Kubestack to manage our AKS clusters within a fairly complex hybrid cloud/on-prem environment. Because the on premises resources we need to access from within the cluster are in a 10.10.10.0/24 subnet, and the vnets created automatically by the AKS managed service have an addressable space of 10.0.0.0/8, which contains 10.10.10.0/24, the collision of these address spaces have prevented us from creating a VPN gateway to link the AKS vnet and the local subnet. Using CNI will allow us to create a vnet with a smaller address space that we can configure and manage as needed.

**Detail**

To enable this behavior, the following changes would be needed:

* The user would create a custom vnet and subnet (outside the Kubestack directory, in a wider TF project?)
* The user would pass the subnet ID in to Kubestack (via config.auto.tfvars?)
* The user would pass in, minimally, values for `service_cidr` and `dns_server_ip` (optionally also `network_plugin`, `network_policy`, and `pod_cidr`)

**Challenge**

In order to complete the CNI setup, the user will need to associate the network security group which is generated by the AKS managed service with the custom subnet. Unfortunately the group name includes a randomly generated number, i.e. `aks-agentpool-22342344-nsg`, and the azurerm_kubernetes_cluster provider does not expose this group name directly within the Terraform state. It is possible to retrieve it using an external data provider and a brief shell script. To facilitate this, it would be helpful if the Kubestack cluster module could expose the name of the auto-created `node_resource_group` that contains the NSG.

**Comment by pst** [comment]
I haven't looked into this yet but your approach sounds very sound. Regarding the generated nsg, maybe there is a data source available to query those? The downside of external data providers is, they have the risk of not working in CI/CD. Since Kubestack bundles all dependencies in the container image this is easy enough.

But support for Terrafom cloud is a goal and there the scripts are problematic. May or may not work. I'd prefer to avoid adding more of those, we already have one in the GKE module. See #116 for more details on this.

**Comment by pst** [comment]
But ultimately, I'd not discourage you from contributing. So if you wanna give it a shot let's get this going and see what we can do. If we end up needing a script so be it. I don't want to block your progress here with the Terraform Cloud issue.

**Comment by pst** [comment]
Just linking the issue and the PR for future reference #135

**Comment by pst** [comment]
This feature was merged and is released, closing the issue. https://github.com/kbst/terraform-kubestack/releases/tag/v0.12.0-beta.0
