### ISSUE TITLE
GitHub template project for kubestack based local and other cloud providers K8s clusters. 

### ISSUE THREAD

**Issue by abhioncbr** [kbst/terraform-kubestack#134]
I was looking for a way to manage my local kind based k8s cluster with installed required components. I have initially automated the requirement; however, I looked for a better approach and learned about the Kubestack project. 

I did try the Kind Kubestack example, and it worked fine; however, getting it worked without using a container is a bit hacky(compiling and installing in the terraform modules in the local .terraform folder). I thought it would be great if we will GitHub template project with kind and kustomize terraform modules with one terraform stack instead of two, and based on that, the user can easily create local or other cloud-based projects as per the requirement.  

Let me know If you are up with this, and I will be happy to contribute to the corresponding changes. Thanks.

**Comment by pst** [comment]
I provide the container images, to make having the right dependencies at all times easier. Both the team building the kind provider and I for the kustomize provider, are working on getting these into the Terraform registry. Once that's done they'd be auto-downloaded just like any other provider. I'm not sure what you mean by GitHub template, but if you mean bundle the providers in the repository, then that's not something I am interested in.

I am working on local development environments that do not require a separate Terraform configuration (as is currently the case with KinD). The work is happening in the [integratedevenv branch](https://github.com/kbst/terraform-kubestack/tree/integratedevenv) and the [CLI repository](https://github.com/kbst/kbst) mostly. I am hoping to release this next week.

**Comment by abhioncbr** [comment]
Thanks. The best is to get the provider from the Terraform registry. Yeah, I was talking about bundling the providers in the repository and thanks for clarifying that. closing the ticket.
