### ISSUE TITLE
Update Get Started tutorial

### ISSUE THREAD

**Issue by Izeka** [kbst/terraform-kubestack#142]
The  **.github/workflows/main.yaml** pipeline at the Get Started tutorial should be updated now that new repositories are named "main" instead of "master", I tried this change and it seems to be working:

 ` github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/apps-deploy-')`

without this change, Terraform apply won't  run in the ops cluster when merging into master

**Comment by pst** [comment]
Thanks for reporting this, I will take care of updating this.

**Comment by pst** [comment]
I've updated it to `main`. I don't think the `master` case is required anymore given all new repo's will default to main and existing repo's keep their existing pipeline file.
