### ISSUE TITLE
GKE Service Account Name to Long

### ISSUE THREAD

**Issue by meggieveggie** [kbst/terraform-kubestack#145]
# Problem

The service account name that is created, has a limit of 28 characters, this means that if your workspace name is to long i.e (kubestack-staging) when you run apply you will get the following error:

```bash
Acquiring state lock. This may take a few moments...
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
module.gke_zero.module.cluster.data.external.gcloud_account: Refreshing state...
module.gke_zero.module.cluster.data.google_client_config.default: Refreshing state...
module.gke_zero.module.cluster.module.cluster_services.data.kustomization.current: Refreshing state...
------------------------------------------------------------------------
Error: "account_id" ("sp-kubestack-staging-us-central1") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"
  on .terraform/modules/gke_zero/google/_modules/gke/service_account.tf line 1, in resource "google_service_account" "current":
   1: resource "google_service_account" "current" {
```

# Short term workaround

Obviously the work around is to minimize the workspace name, however if this is the proposed solution organisations might have to change naming standards (i.e a organisation that is using `staging` everywhere would need to start using `stg`). This should then be documented

# Proposed fix

I am not sure about the complexity that this would create, but a potential fix would be to remove the region that is added as the suffix thus allowing for more flexibility in naming conventions

**Comment by pst** [comment]
I see your point, I also agree the immediate solution is to keep the `name_prefix` and `workspace` short. Instead of shortening `staging -> stg`, you can shorten or remove `kubestack -> kbst`.

The metadata module includes region as part of the cluster name to ensure multi-region. One option to consider could be to have a parameter that disables automatically including the region and then leaves it to users to use the `name_prefix` to avoid name collisions.

This is from the top of my head, if it really works will need some more thought and thorough testing. For reference, this is where the "magic" happens: https://github.com/kbst/terraform-kubestack/blob/master/common/metadata/main.tf

**Comment by meggieveggie** [comment]
Maybe an idea here could be to have a `name_short` that could be used when specifying a configuration that would be used instead of the `metadata.name` 

That way it could be reusable throughout the module

**Comment by pst** [comment]
If the issue is only with the service account (I don't know if it is), it would be an option to have the name not just be the cluster name but be, e.g. something with a 7 char hash of the cluster name as a suffix to make it unique.

**Comment by meggieveggie** [comment]
I believe this issue is only on the service account as I did not experience it anywhere else. Would you like me to open a PR?

**Comment by pst** [comment]
Sure, in that case trying something to keep the SA name below the limit is worth a try. We need to be mindful about the upgrade path for existing clusters though.

**Comment by pst** [comment]
0.13's new custom validation could also be an option here: https://www.terraform.io/docs/configuration/variables.html#custom-validation-rules
