### ISSUE TITLE
Add ability to set the cluster version in Terraform for EKS

### ISSUE THREAD

**Issue by Spazzy757** [kbst/terraform-kubestack#164]
## Problem 

I have a need to set a previous cluster version of EKS

## Solutions

The solutions should be as simple as exposing the value on the [resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#version) However I am not sure how you would be able to leave it blank if you wanted to just use the latest version

**Comment by pst** [comment]
You can default the variable to `null`. For me, main question is how does this relate to EKS updates. Or does EKS not get automatic updates?

**Comment by Spazzy757** [comment]
> You can default the variable to `null`. For me, main question is how does this relate to EKS updates. Or does EKS not get automatic updates?

As far as I understand it you dont get automatic updates

**Comment by Spazzy757** [comment]
Im going to pick this up as I have some time
