### ISSUE TITLE
AWS EKS root_device_volume_size not working

### ISSUE THREAD

**Issue by cbek** [kbst/terraform-kubestack#192]
I set `root_device_volume_size` attribute but it isn't reflected in the terraform run. 
```
clusters = {
  eks_zero = {
    # apps environment
    apps = {
      root_device_volume_size = 60

    }
  }
}

```

**Comment by pst** [comment]
Thanks for reporting. This is an error in the documentation: https://www.kubestack.com/framework/documentation/cluster-module-configuration

https://github.com/kbst/terraform-kubestack/blob/master/aws/cluster/configuration.tf#L27

**Comment by pst** [comment]
Fixed, the documentation update will be released with the next framework version.
