### ISSUE TITLE
GKE: Egress IP Changes on cluster recreate

### ISSUE THREAD

**Issue by Spazzy757** [kbst/terraform-kubestack#218]
# Problem

When you recreate the cluster the NAT gateway generates a New IP for Egress traffic as the `AUTO_ONLY` on `source_subnetwork_ip_ranges_to_nat` is set. For our use case we use this to whitelist against providers we deal with and need this to be more stable. 

# Potential Solution

allow setting `source_subnetwork_ip_ranges_to_nat` to "MANUAL_ONLY" and passing through a "self link" to `nat_ips`. This will allow someone to specify an egress IP instead of it being autocreated

**Comment by Spazzy757** [comment]
Just a note this will also allow to set multiple egress IP's that will help with large volumes of egress traffic and how the port/ip mapping works

**Comment by Spazzy757** [comment]
Seems the issue with passing in the `nat_ips` is that they depend on the subnet that the module creates.

**Comment by Spazzy757** [comment]
So another update on this, setting `AUTO_ONLY` also auto-scales IP's so based on how many nodes you have in your cluster it starts spinning up new IP addresses

So after some playing around I fell on this [fix](https://github.com/PentoHQ/terraform-kubestack/blob/set-manual-ip-on-nat/google/_modules/gke/network.tf#L7-L44), it allows you to specify how many Egress IP addresses you want and attaches them to the Nat gateway. Any thoughts on how to make this backwards compatible for users?

**Comment by pst** [comment]
I'd try a conditional on the length of the compute address resource, and if that's zero set the nap_ips attribute to 0.

Similar to this: https://github.com/kbst/terraform-kubestack/blob/eksnodepools/aws/cluster/node-pool/vpc.tf#L9

**Comment by Spazzy757** [comment]
Okay awesome! :+1: I [updated to be backwards](https://github.com/PentoHQ/terraform-kubestack/blob/set-manual-ip-on-nat/google/_modules/gke/network.tf#L7-L44) compatible, I'll open up a PR for the changes so you can check it out
