### ISSUE TITLE
AKS: disable log analytics

### ISSUE THREAD

**Issue by to266** [kbst/terraform-kubestack#219]
It would be nice to be able to disable log analytics for an AKS cluster. As far as I can tell, right now it's not customizable via kubestack

**Comment by timonbimon** [comment]
for more context: we currently log a lot so using log analytics (even though we don't want to) costs us a lot of money, which essentially means we cannot rely on kubestack to manage our infrastructure any more, as it would automatically re-create the analytics for our cluster.

**Comment by pst** [comment]
I have no objection against making this configurable using a variable.
