### ISSUE TITLE
Error using latest azuread provider

### ISSUE THREAD

**Issue by feend78** [kbst/terraform-kubestack#227]
We recently ran a `terraform init -upgrade` on our kubestack project, and when using the latest version of the `azuread` provider (2.6.0), We receive the following error when running `terraform plan`:

```
Error: Unsupported argument
  on .terraform/modules/aks_zero/azurerm/_modules/aks/service_principal.tf line 25, in resource "azuread_service_principal_password" "current":
  25:   end_date_relative    = var.service_principal_end_date_relative

An argument named "end_date_relative" is not expected here.
```

Looking at the azuread provider documentation, it appears the `end_date_relative` property was removed in the 2.0 version of the provider and replaced with a new `time_rotating` resource that is passed in to the `azuread_service_principal_password` resource.

**Comment by waylew-lexis** [comment]
hello, having same issue. when can we expect a release?

**Comment by pst** [comment]
I'm preparing a release, currently in testing and fixing release blockers. I hope to get it out next weekend.

**Comment by pst** [comment]
https://github.com/kbst/terraform-kubestack/releases/tag/v0.16.0-beta.0
