### ISSUE TITLE
azure aks default node pool availability_zones

### ISSUE THREAD

**Issue by ajrpayne** [kbst/terraform-kubestack#252]
Not sure this is a needed feature, but 

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#default_node_pool

allows setting the availability_zones for the default node pool.

The node_pool module allows settings availability_zones, but I don't see a way to set this for the default node pool.

I also don't know if this is something anyone or I need, but thought worth mentioning.

**Comment by pst** [comment]
It's also my understanding, that the node pool by default uses the zones of the cluster. And I'm not sure if there is a use-case where it makes sense to have it differently.

But I don't oppose having additional configuration, in case somebody wants to control the zones for the pool individually. I'll mark this as a good first issue, so in case someone needs this, they know they can easily contribute it.

**Comment by ajrpayne** [comment]
> It's also my understanding, that the node pool by default uses the zones of the cluster. And I'm not sure if there is a use-case where it makes sense to have it differently.

Is there a way to set the zones of the cluster in kubestack? My default pools all say none for zones.
