### ISSUE TITLE
GKE: Enable cluster Load Balacing - Can't use Container Native Load Balancer in GKE

### ISSUE THREAD

**Issue by anggutie-dev** [kbst/terraform-kubestack#266]
Trying to use "Container Native LoadBalancer"

How can I enable/disable "Load Balancing" addon?

As far as I can tell, these parameters are hardcoded and cannot be modified

folder file: google/_modules/gke/cluster.tf
`  addons_config {
    http_load_balancing {
      disabled = true
    }`

Please confirm!

**Comment by pst** [comment]
I confirm.
