### ISSUE TITLE
EKS:AMI name for creating EKS WorkerNode is different in eu-central-1

### ISSUE THREAD

**Issue by ebalakumar** [kbst/terraform-kubestack#28]
Hello Team , 

https://github.com/kbst/terraform-kubestack/blob/master/aws/_modules/eks/workers_asg.tf

The filter provided for retrieving the  AMI for creating EKS Worked node is not working for **eu-central-1** region. It's not retrieving any AMI .

`aws ec2 --region eu-central-1 describe-images --filters "Name=name,Values=amazon-eks-node*" --owner 602401143452`

> {
>     "Images": []
> }

When tried the same from us-west-2 regions . It is able to retrieve results. 

**The reason being . The EKS-worker-node AMIs in eu-central-1 are having the EKS-K8s versions in it .**

  "Name": "amazon-eks-node-**1.11**-v20190109"

So the filter value has to be 

`["amazon-eks-node-${aws_eks_cluster.current.version}-v*"]
`

```
{
            "Architecture": "x86_64",
            "CreationDate": "2019-01-10T00:31:41.000Z",
            "ImageId": "ami-010caa98bae9a09e2",
            "ImageLocation": "602401143452/amazon-eks-node-1.11-v20190109",
            "ImageType": "machine",
            "Public": true,
            "OwnerId": "602401143452",
            "State": "available",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/xvda",
                    "Ebs": {
                        "DeleteOnTermination": true,
                        "SnapshotId": "snap-0cb69b54efae33948",
                        "VolumeSize": 20,
                        "VolumeType": "gp2",
                        "Encrypted": false
                    }
                }
            ],
            "Description": "EKS Kubernetes Worker AMI with AmazonLinux2 image",
            "EnaSupport": true,
            "Hypervisor": "xen",
            "Name": "amazon-eks-node-1.11-v20190109",
            "RootDeviceName": "/dev/xvda",
            "RootDeviceType": "ebs",
            "SriovNetSupport": "simple",
            "VirtualizationType": "hvm"
        }

```

Please make the corresponding changes so that it works for eu-central-1 region as well.

**Comment by pst** [comment]
Thanks for reporting this - will work on the fix.

**Comment by pst** [comment]
Fix is merged into master and will go into the next release. Probably next week. Until then, anyone facing this problem can specify the commit as the module source like this:

```
source = "github.com/kbst/terraform-kubestack//aws/cluster?ref=aa97a8a7ca20514958b82ae2e1744ce985f8b875"
```

Thanks again @ebalakumar.
