### ISSUE TITLE
Bare metal support?

### ISSUE THREAD

**Issue by elgalu** [kbst/terraform-kubestack#284]
Does this project support bare metal K8s clusters?

**Comment by pst** [comment]
I only support managed K8s offerings AKS, EKS and GKE. I could imagine supporting Cluster API in the future, but not unless there is either a client project sponsoring it, or somebody contributing it.

As for the EKS anywhere, Azure Arc or Google Anthos on-premise stories, I haven't looked into them much. But from what I have seen, it seems the setup boils down to, download our binaries and put them on your machines. Then connect to our cloud. This is not something that Kubestack will support.

Kubestack requires an API it can talk to and say, give me a Kubernetes cluster. Apart from Cluster API, I have not yet seen anything that comes close to this on-prem.

I am not interested in becoming yet another tool that turns servers into Kubernetes clusters. There is no shortage of tools that do that. And Terraform is a poor choice for this task anyway.

**Comment by elgalu** [comment]
Great points!
