### ISSUE TITLE
Cert-Manager Module: Wait for Resources

### ISSUE THREAD

**Issue by a-priestley** [kbst/terraform-kubestack#318]
Hello,

I'm attempting to use `kbst.xyz/catalog/cert-manager/kustomization` as defined below:

<details>

```tf
terraform {
  required_providers {
    kustomization = {
      source = "kbst/kustomization"
    }
  }
}

provider "kustomization" {
  alias = "local"
  kubeconfig_raw = var.kube_config
}

resource "kustomization_resource" "dns_api_token_secret" {
  provider = kustomization.local
  manifest = jsonencode({
    apiVersion = "v1"
    kind       = "Secret"
    metadata = {
      name      = "${var.dns_provider_name}-api-token"
      namespace = "cert-manager"
    }
    type = "Opaque"
    stringData = {
      api-token = "${var.dns_api_token}"
    }
  })
}


module "cert_manager" {
  providers = {
    kustomization = kustomization.local
  }

  source  = "kbst.xyz/catalog/cert-manager/kustomization"
  version = "1.11.1-kbst.0"

  configuration_base_key = "default"
  configuration = {
    default = {
      additional_resources = ["${path.module}/cluster-issuer.yaml"]
      patches = [
        {
          patch = <<-EOF
            - op: replace
              path: /spec/acme/email
              value: ${var.email}
          EOF

          target = {
            group  = "cert-manager.io"
            verion = "v1"
            kind   = "ClusterIssuer"
            name   = "letsencrypt"
          }
        },
        {
          patch = <<-EOF
            - op: replace
              path: /spec/acme/solvers/0/dns01/${var.dns_provider_name}/apiTokenSecretRef/name
              value: ${yamldecode(kustomization_resource.dns_api_token_secret.manifest)["metadata"]["name"]}
          EOF
          target = {
            group  = "cert-manager.io"
            verion = "v1"
            kind   = "ClusterIssuer"
            name   = "letsencrypt"
          }
        }
      ]
    }
  }
}

resource "kustomization_resource" "certificate" {
  provider = kustomization.local
  manifest = jsonencode({
    apiVersion = "cert-manager.io/v1"
    kind       = "Certificate"
    metadata = {
      name      = var.full_domain
      namespace = "cert-manager"
    }
    spec = {
      secretName = "${var.full_domain}-tls"
      issuerRef = {
        name = "letsencrypt"
        kind = "ClusterIssuer"
      }
      commonName = "*.${var.full_domain}"
      dnsNames = [
        "*.${var.full_domain}",
        "${var.full_domain}",
      ]
    }
  })
  depends_on = [module.cert_manager]
}
```

</details>

At the moment, this is a two-stage deploy. Given a blank Terraform state, the module will create upon applying the code, but the certificate will fail with error:
`github.com/kbst/terraform-provider-kustomize/kustomize.kustomizationResourceDiff: "cert-manager.io/Certificate/cert-manager/rdtest2.rutterconnect.net": Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook`

A second run allows the certificate to be pulled down successfully.

`depends_on = [module.cert_manager]` unfortunately does not solve the issue. And outputting the module results in an empty object.

Is there a way to deploy this in one shot?

Thanks!

**Comment by pst** [comment]
For the secret, I'd use a secret_generator (https://www.kubestack.com/framework/documentation/extending-kubestack/#kubernetes-manifests) and for the certificate I'd use additional_resources. There's also [this guide](https://www.kubestack.com/guides/cert-manager-issue-letsencrypt-certificates-kubernetes-terraform/) that has some relevant example. Data sources and for_each, both of which the provider/modules rely on heavily do have a number of edge cases. You have to be mindful of that.

The webhook issue can happen, I don't think there is a way to avoid this reliably.
