### ISSUE TITLE
AKS: Add node pools when upstream supports it

### ISSUE THREAD

**Issue by pst** [kbst/terraform-kubestack#46]
Upstream issue: https://github.com/Azure/AKS/issues/287

**Comment by pst** [comment]
The azurerm provider now has support for [multiple agent profiles](https://github.com/terraform-providers/terraform-provider-azurerm/pull/3491). However, these are configured as blocks in the cluster resource and that makes it hard to expose them through a module. [Dynamic blocks](https://github.com/hashicorp/terraform/issues/7034#issuecomment-433511035) available from TF 0.12 should help.

Unfortunately this means, I have to do the 0.12 upgrade before I can finish node pools across all providers.

**Comment by pst** [comment]
TF 0.12 upgrade PR #61

**Comment by pst** [comment]
https://github.com/kbst/terraform-kubestack/issues/172

**Comment by jeacott1** [comment]
this is now available in aks
ref: https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools

**Comment by jeacott1** [comment]
@pst any plans to revisit this issue?

**Comment by pst** [comment]
Included in latest release: https://github.com/kbst/terraform-kubestack/releases/tag/v0.16.0-beta.0
