### ISSUE TITLE
GKE: Make autoscaling the default for clusters

### ISSUE THREAD

**Issue by pst** [kbst/terraform-kubestack#6]
Goal of the Kubestack modules is to harmonize the managed K8s solutions across the different cloud providers as much as possible. This should be reflected in the input variables too. Currently EKS has min, max node settings. The GKE module does not currently enable the autoscaler and does not expose the min, max variables.

**Comment by jonathangold** [comment]
@pst I'd like to take a stab at this. Will give it a shot later today.

**Comment by pst** [comment]
After looking into this, there are two related features.
 * cluster_autoscaling, which creates node pools (beta)
 * and autoscaling a node pool, which seems not to be possible with the default node pool

That being said, I suggest we start with first adding support for #8 and make sure additiona node pools can be created as autoscaling.

And we revisits the cluster-autoscaling feature when it's out of beta.

**Comment by pst** [comment]
Well, in the UI I can set the default node pool to autoscaling. But I can't seem to find a attribute in TF to do the same. https://www.terraform.io/docs/providers/google/r/container_cluster.html#disk_size_gb

**Comment by pst** [comment]
To make this even weirder. When enabling autoscaling in the UI a subsequent TF run does not recognize any differences.
