### ISSUE TITLE
Support `--validate=false` flag for `kubectl apply` on some manifests

### ISSUE THREAD

**Issue by mircea-cosbuc** [kbst/terraform-kubestack#72]
For k8s versions below 1.16, installing `cert-manager` requires running `kubectl apply -f` with the `--validate=false` flag ([cert-manager install docs](https://docs.cert-manager.io/en/latest/getting-started/install/kubernetes.html)). Opening this issue to figure out the best way to make this possible while including `cert-manager` in the manifests.

**Comment by chauffer** [comment]
The file doing `kubectl apply`: https://github.com/kbst/terraform-kubestack/blob/4e008fb8b8b8d2ed61a04f6b6adb82d89ee539d1/common/cluster_services/kubectl_apply.sh

**Comment by mircea-cosbuc** [comment]
Another issue relevant to installing `cert-manager` in a gitops context https://github.com/jetstack/cert-manager/issues/2197, they're hitting a similar issue.

**Comment by pst** [comment]
Would the solution be to just update the kubectl version then? https://github.com/kbst/terraform-kubestack/blob/master/quickstart/src/ci-cd/Dockerfile



I don't think disabling validation is a good idea. Rather we should try and work with upstream cert-manager and contribute a solution there. I left a comment to ask for some more info on the field supposedly causing this. https://github.com/jetstack/cert-manager/issues/2197#issuecomment-549529982
