### ISSUE TITLE
Can no longer get DNS information

### ISSUE THREAD

**Issue by youngnicks** [kbst/terraform-kubestack#73]
The current documentation states that to get the required DNS information, you need to run `terraform output --module...`.  However, when running this with Terraform 0.12+ you get the following error:
```
Error: Unsupported option

The -module option is no longer supported since Terraform 0.12, because now
only root outputs are persisted in the state.
```

The Terraform documentation states that you must now specify outputs by adding:
```
output "fqdn" {
  value = module.cluster_metadata.fqdn
}
```
and then access it via `terraform output fqdn`.

Another output for `ingress_zone_name_servers` is also needed.

**Comment by youngnicks** [comment]
Digging further, it looks like these have been added to the code. The documentation just needs to be updated on how to access these variables.

**Comment by pst** [comment]
Yes indeed, I forgot to correctly update the website. I will look into this. It may be that exposing the outputs all the way to the root module may require an extra step apart from config and module each time somebody adds a new cluster. Which is something I'd like to avoid.

In the meantime you can just `terraform state show` with a bit of `grep` or `jq` to find the values.

**Comment by pst** [comment]
I have replaced the `terraform output` with a `terraform state show` of the respective DNS zone resource in the quickstart. This does not require passing the output all the way through to the root module, which would require users to do this for every one of their cluster pairs.
