### ISSUE TITLE
Error while executing `terraform apply`

### ISSUE THREAD

**Issue by jonatasbaldin** [kbst/terraform-kubestack#88]
Hi there,

Following the [quickstart documentation](https://www.kubestack.com/infrastructure/documentation/quickstart) in the step `3. Bootstrap the Ops-and Apps-cluster pair` I got the following error:

```bash
$ terraform apply --auto-approve

module.gke_zero.module.cluster.data.external.gcloud_account: Refreshing state...
module.gke_zero.module.cluster.data.google_client_config.default: Refreshing state...
module.gke_zero.module.cluster.module.cluster_services.data.kustomization.current: Refreshing state...

Error: Failed to initialize config: invalid configuration: no configuration has been provided

  on .terraform/modules/gke_zero/google/_modules/gke/provider.tf line 4, in provider "kubernetes":
   4: provider "kubernetes" {
```

Am I forgetting some configuration or could this be a bug?

Cheers!

**Comment by pst** [comment]
Unfortunately you are the only person that has the necessary information to retrace your steps and figure out if you are forgetting something. I don't see how I can help here.
